# Generated by Django 2.0.6 on 2019-05-29 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.FileField(blank=True, upload_to='images')),
                ('entry', models.TextField(default='', max_length=5000)),
                ('video', models.FileField(blank=True, upload_to='videos', verbose_name='')),
                ('URL_link', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.FileField(upload_to='images')),
                ('imageDetails', models.TextField(blank=True, max_length=400)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('cover', models.FileField(upload_to='books')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('profilePic', models.FileField(blank=True, upload_to='profilePics')),
                ('moto', models.CharField(blank=True, max_length=300)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NaniEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.FileField(blank=True, upload_to='images')),
                ('entry', models.TextField(default='', max_length=5000)),
                ('video', models.FileField(null=True, upload_to='videos', verbose_name='')),
                ('URL_link', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEventsEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('flyer', models.FileField(upload_to='flyers')),
            ],
        ),
    ]
