# Generated by Django 2.0.6 on 2019-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commententrymodel',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
