# Generated by Django 2.0.6 on 2019-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0002_auto_20190530_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commententrymodel',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
