# Generated by Django 2.0.6 on 2019-05-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0003_auto_20190530_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingeventsentrymodel',
            old_name='flyer',
            new_name='eventFlyer',
        ),
    ]
