# Generated by Django 2.0.6 on 2019-05-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0004_auto_20190530_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingeventsentrymodel',
            name='eventFlyer',
            field=models.FileField(upload_to='images'),
        ),
    ]
