# Generated by Django 2.0.6 on 2019-05-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0006_auto_20190530_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanientrymodel',
            name='URL_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='nanientrymodel',
            name='entry',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='nanientrymodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name=''),
        ),
    ]
