# Generated by Django 2.0.6 on 2019-05-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0007_auto_20190531_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionentrymodel',
            name='URL_link',
            field=models.URLField(),
        ),
    ]
