# Generated by Django 2.0.6 on 2019-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0008_auto_20190531_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanientrymodel',
            name='URL_link',
            field=models.URLField(),
        ),
    ]
