# Generated by Django 2.0.6 on 2019-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0009_auto_20190603_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionentrymodel',
            name='URL_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='nanientrymodel',
            name='URL_link',
            field=models.URLField(blank=True),
        ),
    ]
