# Generated by Django 2.0.6 on 2019-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0011_auto_20190603_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionentrymodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='nanientrymodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
