# Generated by Django 2.0.6 on 2019-06-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0012_auto_20190603_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionentrymodel',
            old_name='image',
            new_name='DiscussionImage',
        ),
        migrations.RenameField(
            model_name='nanientrymodel',
            old_name='image',
            new_name='naniImage',
        ),
    ]
