# Generated by Django 2.0.6 on 2019-06-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0013_auto_20190603_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionentrymodel',
            old_name='DiscussionImage',
            new_name='discussionImage',
        ),
    ]
