# Generated by Django 2.0.6 on 2019-06-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0014_auto_20190603_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nanientrymodel',
            old_name='video',
            new_name='naniVideo',
        ),
    ]
