# Generated by Django 2.0.6 on 2019-06-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0016_auto_20190603_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanientrymodel',
            name='image',
            field=models.FileField(default='', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='nanientrymodel',
            name='video',
            field=models.FileField(default='', null=True, upload_to='videos'),
        ),
    ]
