# Generated by Django 2.0.6 on 2019-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0017_auto_20190603_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanientrymodel',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='nanientrymodel',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos'),
        ),
    ]
