# Generated by Django 2.0.6 on 2019-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0019_auto_20190603_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanientrymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
