# Generated by Django 2.0.6 on 2019-06-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionApp', '0020_auto_20190603_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipEntryModel',
        ),
    ]
